const rabbit = require("./rabbit_transmitter");

async function run(transmit) {
  transmit({
    i_effectiveness: "4.9",
    i_communication: "4.8",
    i_class_time: "4.8",
    i_recommend: "4.9",
    i_enthusiasm: "5.0",
    c_learning: "4.8",
    c_textbook_eff: "4.2",
    c_lecture_eff: "4.6",
    c_assn_eff: "4.3",
    c_textbook_req: "4.3",
    c_intellectual: "4.8",
    d_learning: "4.6",
    d_textbook_eff: "4.0",
    d_lecture_eff: "4.5",
    d_assn_eff: "4.5",
    d_textbook_req: "4.1",
    d_intellectual: "4.5",
    d_effectiveness: "4.7",
    d_communication: "4.7",
    d_class_time: "4.6",
    d_recommend: "4.6",
    d_enthusiasm: "4.9",
    name: "Maletta, Mario",
    course_name: "Planng/Budgeting for Innovatn",
    subject: "ACCT",
    course_number: "6280",
    enrollment: "13",
    responses_w_declines: "12",
    declines: "0",
    is_summer: false,
    hours_per_week: "11.140"
  });
  transmit({
    i_effectiveness: "4.4",
    i_communication: "4.5",
    i_class_time: "4.3",
    i_recommend: "4.1",
    i_enthusiasm: "4.7",
    c_learning: "4.3",
    c_textbook_eff: "4.3",
    c_lecture_eff: "4.3",
    c_assn_eff: "4.7",
    c_textbook_req: "4.3",
    c_intellectual: "4.2",
    d_learning: "4.6",
    d_textbook_eff: "4.0",
    d_lecture_eff: "4.5",
    d_assn_eff: "4.5",
    d_textbook_req: "4.1",
    d_intellectual: "4.5",
    d_effectiveness: "4.7",
    d_communication: "4.7",
    d_class_time: "4.6",
    d_recommend: "4.6",
    d_enthusiasm: "4.9",
    name: "Williams, Christina",
    course_name: "Fin Reptg & Manag Dec Mkg 2",
    subject: "ACCT",
    course_number: "6201",
    enrollment: "37",
    responses_w_declines: "14",
    declines: "0",
    is_summer: false,
    hours_per_week: "9.275"
  });
  transmit({
    i_effectiveness: "5.0",
    i_communication: "5.0",
    i_class_time: "5.0",
    i_recommend: "5.0",
    i_enthusiasm: "5.0",
    c_learning: "5.0",
    c_textbook_eff: "0.0",
    c_lecture_eff: "5.0",
    c_assn_eff: "5.0",
    c_textbook_req: "0.0",
    c_intellectual: "5.0",
    d_learning: "4.6",
    d_textbook_eff: "4.0",
    d_lecture_eff: "4.5",
    d_assn_eff: "4.5",
    d_textbook_req: "4.1",
    d_intellectual: "4.5",
    d_effectiveness: "4.7",
    d_communication: "4.7",
    d_class_time: "4.6",
    d_recommend: "4.6",
    d_enthusiasm: "4.9",
    name: "Powell, Joanna",
    course_name: "Advanced Topics in Accounting",
    subject: "ACCT",
    course_number: "6262",
    enrollment: "9",
    responses_w_declines: "1",
    declines: "0",
    is_summer: false,
    hours_per_week: "6.500"
  });
  transmit({
    i_effectiveness: "0.0",
    i_communication: "0.0",
    i_class_time: "0.0",
    i_recommend: "0.0",
    i_enthusiasm: "0.0",
    c_learning: "0.0",
    c_textbook_eff: "0.0",
    c_lecture_eff: "0.0",
    c_assn_eff: "0.0",
    c_textbook_req: "0.0",
    c_intellectual: "0.0",
    d_learning: "4.6",
    d_textbook_eff: "4.0",
    d_lecture_eff: "4.5",
    d_assn_eff: "4.5",
    d_textbook_req: "4.1",
    d_intellectual: "4.5",
    d_effectiveness: "4.7",
    d_communication: "4.7",
    d_class_time: "4.6",
    d_recommend: "4.6",
    d_enthusiasm: "4.9",
    name: "Cahill, Catherine",
    course_name: "Advanced Topics in Accounting",
    subject: "ACCT",
    course_number: "6262",
    enrollment: "5",
    responses_w_declines: "0",
    declines: "0",
    is_summer: false,
    hours_per_week: "0.000"
  });
  transmit({
    i_effectiveness: "4.8",
    i_communication: "4.9",
    i_class_time: "4.9",
    i_recommend: "4.9",
    i_enthusiasm: "4.9",
    c_learning: "4.7",
    c_textbook_eff: "3.7",
    c_lecture_eff: "4.7",
    c_assn_eff: "4.7",
    c_textbook_req: "3.7",
    c_intellectual: "4.4",
    d_learning: "4.6",
    d_textbook_eff: "4.0",
    d_lecture_eff: "4.5",
    d_assn_eff: "4.5",
    d_textbook_req: "4.1",
    d_intellectual: "4.5",
    d_effectiveness: "4.7",
    d_communication: "4.7",
    d_class_time: "4.6",
    d_recommend: "4.6",
    d_enthusiasm: "4.9",
    name: "Zullo, Ronald",
    course_name: "Tax Procedure & Ethics",
    subject: "ACCT",
    course_number: "6234",
    enrollment: "7",
    responses_w_declines: "7",
    declines: "0",
    is_summer: false,
    hours_per_week: "8.780"
  });
  transmit({
    i_effectiveness: "4.8",
    i_communication: "4.7",
    i_class_time: "4.8",
    i_recommend: "4.9",
    i_enthusiasm: "4.8",
    c_learning: "4.8",
    c_textbook_eff: "4.2",
    c_lecture_eff: "4.7",
    c_assn_eff: "4.9",
    c_textbook_req: "4.0",
    c_intellectual: "4.5",
    d_learning: "4.4",
    d_textbook_eff: "3.9",
    d_lecture_eff: "4.1",
    d_assn_eff: "4.4",
    d_textbook_req: "3.9",
    d_intellectual: "4.3",
    d_effectiveness: "4.3",
    d_communication: "4.3",
    d_class_time: "4.3",
    d_recommend: "4.3",
    d_enthusiasm: "4.6",
    name: "Mihajlovikj, Vidoje",
    course_name: "Algorithms",
    subject: "CS",
    course_number: "5006",
    enrollment: "30",
    responses_w_declines: "23",
    declines: "0",
    is_summer: false,
    hours_per_week: "15.555"
  });
  transmit({
    i_effectiveness: "4.7",
    i_communication: "4.8",
    i_class_time: "4.7",
    i_recommend: "4.7",
    i_enthusiasm: "4.9",
    c_learning: "4.8",
    c_textbook_eff: "4.2",
    c_lecture_eff: "4.6",
    c_assn_eff: "4.7",
    c_textbook_req: "4.2",
    c_intellectual: "4.5",
    d_learning: "4.4",
    d_textbook_eff: "3.9",
    d_lecture_eff: "4.1",
    d_assn_eff: "4.4",
    d_textbook_req: "3.9",
    d_intellectual: "4.3",
    d_effectiveness: "4.3",
    d_communication: "4.3",
    d_class_time: "4.3",
    d_recommend: "4.3",
    d_enthusiasm: "4.6",
    name: "Mihajlovikj, Vidoje",
    course_name: "Algorithms",
    subject: "CS",
    course_number: "5006",
    enrollment: "65",
    responses_w_declines: "60",
    declines: "0",
    is_summer: false,
    hours_per_week: "15.540"
  });
  transmit({
    i_effectiveness: "3.6",
    i_communication: "3.2",
    i_class_time: "3.1",
    i_recommend: "3.2",
    i_enthusiasm: "4.3",
    c_learning: "3.6",
    c_textbook_eff: "3.3",
    c_lecture_eff: "2.9",
    c_assn_eff: "3.7",
    c_textbook_req: "3.4",
    c_intellectual: "4.1",
    d_learning: "4.4",
    d_textbook_eff: "3.9",
    d_lecture_eff: "4.1",
    d_assn_eff: "4.4",
    d_textbook_req: "3.9",
    d_intellectual: "4.3",
    d_effectiveness: "4.3",
    d_communication: "4.3",
    d_class_time: "4.3",
    d_recommend: "4.3",
    d_enthusiasm: "4.6",
    name: "Slaughter, Adrienne",
    course_name: "Algorithms",
    subject: "CS",
    course_number: "5006",
    enrollment: "54",
    responses_w_declines: "15",
    declines: "0",
    is_summer: false,
    hours_per_week: "13.700"
  });
  transmit({
    i_effectiveness: "3.8",
    i_communication: "3.3",
    i_class_time: "4.0",
    i_recommend: "3.7",
    i_enthusiasm: "4.7",
    c_learning: "3.7",
    c_textbook_eff: "1.7",
    c_lecture_eff: "2.0",
    c_assn_eff: "4.0",
    c_textbook_req: "1.0",
    c_intellectual: "5.0",
    d_learning: "4.4",
    d_textbook_eff: "3.9",
    d_lecture_eff: "4.1",
    d_assn_eff: "4.4",
    d_textbook_req: "3.9",
    d_intellectual: "4.3",
    d_effectiveness: "4.3",
    d_communication: "4.3",
    d_class_time: "4.3",
    d_recommend: "4.3",
    d_enthusiasm: "4.6",
    name: "Buck, Joseph",
    course_name: "Algorithms",
    subject: "CS",
    course_number: "5006",
    enrollment: "15",
    responses_w_declines: "3",
    declines: "0",
    is_summer: false,
    hours_per_week: "18.500"
  });
}

if (require.main === module) {
  rabbit.runRabbitScraper(run);
}
